config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :blogs
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true 
  before_validation { email.downcase! }
  has_secure_password
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])

  end
  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to '一覧に戻る', blogs_path %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<%= link_to '一覧に戻る', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>アカウント編集ページ</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email %>
  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "パスワード（確認）" %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit "更新する" %>
<% end %>

<%= link_to "戻る", user_path(@user.id) %>

app/views/users/index.html.erb
<%= link_to t('common.sign_up'), new_user_path, id: "sign-up" %>
<h1>ユーザ一覧</h1>
<table>
  <thead>
    <tr>
      <th><%= "name" %></th>
      <th><%= "email" %></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to t('common.show'), user %></td>
    <td><%= link_to t('common.edit'), edit_user_path(user) %></td>
    <td><%= link_to t('common.destroy'), user, method: :delete, data: { confirm: t('common.confirm_destroy') } %></td>
  </tr>
<% end %>

app/views/users/new.html.erb
<h1>アカウント登録ページ</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email %>
  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "パスワード（確認）" %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit "登録する" %>
<% end %>

app/views/users/show.html.erb
<h1>アカウント詳細ページ</h1>
<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>

<%= link_to "編集", edit_user_path(@user.id) %>
|
<%= link_to "削除",  user_path, method: :delete, data: { confirm: '本当に削除してもよろしいですか?'} %>

<%= link_to "ブログ一覧", blogs_path %>